#!/bin/sh

VF="`dirname "$0"`/dist-version"

if [ -f "$VF" ]; then
  # A distribution with a declared version
  cat "$VF" | tr -d '\n'
else
  # Building from Git
  echo -n "`git describe --dirty | tr - _`"
fi
